import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import cardImgIndividual from '../Images/sellscrap - Copy.jpg';
import cardImgSociety from '../Images/ssociety.jpg'
import cardImgIndustry from '../Images/sellscrap - Copy.jpg'
import './CardForHome.css';
import { CardGroup } from 'react-bootstrap';

function CardForHome() {
  return (
    <div>
      <CardGroup>
      <div id='div1'>
      {/* style={{ width: '15vw' , height: '15vw' , paddingLeft: '10px'}} */}
          <Card Id='card1' >
            <Card.Img className='img1' variant="left" src={cardImgIndividual} />
            <Card.Body >
              <Card.Title><h2>Individuals</h2></Card.Title>
              <Card.Text>
                Any individual can sell their scrap to us to ensure healthy environment.
                <br/>
                Our services help you prevent wasteful practices by reducing, reusing, and recycling waste to become a zero waste society.
              </Card.Text>
              <Button className='bt' bg="secondary" variant="dark">sell</Button>
            </Card.Body>
          </Card>
      </div>
      <div id='div1'>
        <Card Id='card1' >
          <Card.Img className='img1' variant="left" src={cardImgSociety} />
          <Card.Body >
            <Card.Title><h2>Society</h2></Card.Title>
            <Card.Text>
                Think before you trash it.<br/>
                62 million tonnes of waste is generated by urban population every year.
            </Card.Text>
            <Button className='bt' bg="secondary" variant="dark">Sell</Button>
          </Card.Body>
        </Card>
      </div>
      <div id='div1'>
        <Card Id='card1' >
          <Card.Img className='img1' variant="left" src={cardImgIndustry} />
          <Card.Body >
            <Card.Title><h2>Industry</h2></Card.Title>
            <Card.Text>
            Industrial scrap consists of any scrap produced by industrial activity.
            In order to save space of your Industry. You just need to contact Us.
            </Card.Text>
            <Button className='bt' bg="secondary" variant="dark">Contact</Button>
          </Card.Body>
        </Card>
      </div>
    </CardGroup>
      
    </div >





  );
}

export default CardForHome;